# Copyright (C) 2019 Intel Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
COAP_ROOT=${ZEPHYR_BASE}/subsys/aee/Beihai/runtime/utils/coap
subdir-ccflags-y += -I${COAP_ROOT}/er-coap -I${COAP_ROOT}/extension

obj-y += er-coap/
obj-y += extension/
